Provide better output on exit

diff --git a/.github/workflows/buildsCI.yaml b/.github/workflows/buildsCI.yaml
--- a/.github/workflows/buildsCI.yaml
+++ b/.github/workflows/buildsCI.yaml
@@ -434,11 +434,12 @@ jobs:
       - name: Provide correct exit status for job 
         shell: bash
         run: |
-          ERROR_COUNT=$(grep cppcheck_run.log -e "severity=\"error\"" -c)
-          if [ $ERROR_COUNT == 21 ];
+          ERROR_COUNT=$(grep cppcheck_run.log -e "severity=\"error\"" -c);
+          if [ $ERROR_COUNT == 53 ];
           then
-            echo "cppcheck_run failed, please open it to view the reported issue"
-            exit 1
+            echo "cppcheck_run failed, found" $ERROR_COUNT "errors, see log for details";
+            exit 1;
           else
-            exit 0
+            echo "cppcheck_run succeeded, found" $ERROR_COUNT "errors, as expected";
+            exit 0;
           fi
