PR #9487 from Nir: upload test logs on failure, too [GHA]
(cherry picked from commit 9895ddfd2efc1d6752b5d1701f38c9fc6e234054)

diff --git a/.github/workflows/buildsCI.yaml b/.github/workflows/buildsCI.yaml
--- a/.github/workflows/buildsCI.yaml
+++ b/.github/workflows/buildsCI.yaml
@@ -57,12 +57,31 @@ jobs:
      
     - name: Test
       shell: bash
+      id: test-step
+      # We set continue-on-error: true as a workaround for not skipping the upload log step on failure,
+      # The final step will check the return value from the test step and decide if to fail/pass the job
+      continue-on-error: true 
       run: |
+       export LRS_LOG_LEVEL="DEBUG";
        cd build/${{env.LRS_RUN_CONFIG}}
        ls
        ./live-test.exe -d yes -i [software-device]  
-  
-  
+       
+    - name: Upload RS log artifact
+      uses: actions/upload-artifact@v2
+      with: 
+        name: Log file - Windows_testing_cpp_USB_Win7
+        path: build/${{env.LRS_RUN_CONFIG}}/*.log
+        
+    - name: Provide correct exit status for job 
+      shell: bash
+      run: |
+        if [ ${{steps.test-step.outcome}} = "failure" ];then
+           echo "Test step failed, please open it to view the reported issue"
+           exit 1
+        else
+           exit 0
+        fi
   
   Windows_cpp:
     runs-on: windows-2016
@@ -140,50 +159,72 @@ jobs:
         cd build
         cmake --build . --config ${{env.LRS_BUILD_CONFIG}} -- -m     
   Linux_testing_cpp:
-      runs-on: ubuntu-18.04    
-      timeout-minutes: 60
-      env: 
-        RS_CPP_TEST: true
-      steps:
-      - uses: actions/checkout@v2
-      
-      - name: Prebuild
-        shell: bash
-        run: |
-          cd scripts && ./api_check.sh && cd ..
-          mkdir build && cd build
-          export LRS_LOG_LEVEL="DEBUG";
-          url_records_path="https://librealsense.intel.com/rs-tests/lrs_2.8.3/";
-          records_name="records_test.txt";
-          url_records_list=$url_records_path$records_name;
-          wget $url_records_path$records_name;
-          tests_list=`cat $records_name`;
-          for record in $tests_list; do echo $url_records_path$record; wget $url_records_path$record -P "records/"$(echo $record | cut -d '/' -f 1); done;
-          
-          sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test;
-          sudo apt-get update;
-          sudo apt-get install -qq build-essential xorg-dev libgl1-mesa-dev libglu1-mesa-dev libglew-dev libglm-dev;
-          sudo apt-get install -qq libusb-1.0-0-dev;
-          sudo apt-get install -qq libgtk-3-dev;
-          sudo apt-get install gcc-5 g++-5;
-          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5;
-          sudo apt-get install libglfw3-dev libglfw3;
-      
-      - name: Build
-        shell: bash
-        run: | 
-          cd build
-          cmake .. -DBUILD_UNIT_TESTS=false -DBUILD_LEGACY_LIVE_TEST=true -DBUILD_EXAMPLES=false -DBUILD_TOOLS=false -DBUILD_WITH_TM2=false -DCHECK_FOR_UPDATES=true
-          cmake --build . --config ${{env.LRS_RUN_CONFIG}} -- -j4
-          
-      - name: Test
-        shell: bash
-        run: | 
-          cd build    
-          ./unit-tests/live-test -d yes -i [software-device]
-          for i in ./records/single_cam/*; do ./unit-tests/live-test -d yes -i ~[multicam] from "$i"; done
-          for i in ./records/multi_cam/*; do ./unit-tests/live-test -d yes -i [multicam] from "$i"; done
-  
+    runs-on: ubuntu-18.04    
+    timeout-minutes: 60
+    env: 
+      RS_CPP_TEST: true
+    steps:
+    - uses: actions/checkout@v2
+    
+    - name: Prebuild
+      shell: bash
+      run: |
+        cd scripts && ./api_check.sh && cd ..
+        mkdir build && cd build
+        export LRS_LOG_LEVEL="DEBUG";
+        url_records_path="https://librealsense.intel.com/rs-tests/lrs_2.8.3/";
+        records_name="records_test.txt";
+        url_records_list=$url_records_path$records_name;
+        wget $url_records_path$records_name;
+        tests_list=`cat $records_name`;
+        for record in $tests_list; do echo $url_records_path$record; wget $url_records_path$record -P "records/"$(echo $record | cut -d '/' -f 1); done;
+        
+        sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test;
+        sudo apt-get update;
+        sudo apt-get install -qq build-essential xorg-dev libgl1-mesa-dev libglu1-mesa-dev libglew-dev libglm-dev;
+        sudo apt-get install -qq libusb-1.0-0-dev;
+        sudo apt-get install -qq libgtk-3-dev;
+        sudo apt-get install gcc-5 g++-5;
+        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5;
+        sudo apt-get install libglfw3-dev libglfw3;
+    
+    - name: Build
+      shell: bash
+      run: | 
+        cd build
+        cmake .. -DBUILD_UNIT_TESTS=false -DBUILD_LEGACY_LIVE_TEST=true -DBUILD_EXAMPLES=false -DBUILD_TOOLS=false -DBUILD_WITH_TM2=false -DCHECK_FOR_UPDATES=true
+        cmake --build . --config ${{env.LRS_RUN_CONFIG}} -- -j4
+        
+    - name: Test
+      shell: bash
+      id: test-step
+      # We set continue-on-error: true as a workaround for not skipping the upload log step on failure,
+      # The final step will check the return value from the test step and decide if to fail/pass the job
+      continue-on-error: true 
+      run: | 
+        export LRS_LOG_LEVEL="DEBUG";
+        cd build    
+        ./unit-tests/live-test -d yes -i [software-device]
+        for i in ./records/single_cam/*; do ./unit-tests/live-test -d yes -i ~[multicam] from "$i"; done
+        for i in ./records/multi_cam/*; do ./unit-tests/live-test -d yes -i [multicam] from "$i"; done
+        
+
+    - name: Upload RS log artifact
+      uses: actions/upload-artifact@v2
+      with: 
+        name: Log file - Linux_testing_cpp
+        path: build/*.log
+        
+        
+    - name: Provide correct exit status for job 
+      shell: bash
+      run: |
+        if [ ${{steps.test-step.outcome}} = "failure" ];then
+           echo "Test step failed, please open it to view the reported issue"
+           exit 1
+        else
+           exit 0
+        fi
   
   Linux_static_cpp:
       runs-on: ubuntu-18.04
