Add cppcheck step to GitHub actions

diff --git a/.github/workflows/buildsCI.yaml b/.github/workflows/buildsCI.yaml
--- a/.github/workflows/buildsCI.yaml
+++ b/.github/workflows/buildsCI.yaml
@@ -400,4 +400,34 @@ jobs:
        cmake --build . --config ${{env.LRS_BUILD_CONFIG}} -- -j4
        ls
   
-  
+  cppcheck:
+    name: cppcheck-test
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+          
+      - name: cppcheck_run
+        uses: deep5050/cppcheck-action@main
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN}}
+          std: c++11
+          max_ctu_depth: 4
+          output_file: cppcheck_run.log
+          #exclude all third-party libs but `realdds`
+          other_options: -ithird-party third-party/realdds
+          
+      - name: Upload cppcheck log
+        uses: actions/upload-artifact@v3
+        with: 
+          name: cppcheck_log
+          path: cppcheck_run.log
+
+      - name: Provide correct exit status for job 
+        shell: bash
+        run: |
+          if [ ${{steps.cppcheck_run.outcome}} = "failure" ];then
+             echo "cppcheck_run failed, please open it to view the reported issue"
+             exit 1
+          else
+             exit 0
+          fi
