Fix if

diff --git a/.github/workflows/buildsCI.yaml b/.github/workflows/buildsCI.yaml
--- a/.github/workflows/buildsCI.yaml
+++ b/.github/workflows/buildsCI.yaml
@@ -437,9 +437,9 @@ jobs:
           ERROR_COUNT=$(grep cppcheck_run.log -e "severity=\"error\"" -c);
           if [ $ERROR_COUNT == 53 ];
           then
-            echo "cppcheck_run failed, found" $ERROR_COUNT "errors, see log for details";
-            exit 1;
-          else
             echo "cppcheck_run succeeded, found" $ERROR_COUNT "errors, as expected";
             exit 0;
+          else
+            echo "cppcheck_run failed, found" $ERROR_COUNT "errors, see log for details";
+            exit 1;
           fi
