check XML output

diff --git a/.github/workflows/buildsCI.yaml b/.github/workflows/buildsCI.yaml
--- a/.github/workflows/buildsCI.yaml
+++ b/.github/workflows/buildsCI.yaml
@@ -423,7 +423,7 @@ jobs:
       - name: Run
         shell: bash
         run: | 
-          cppcheck . --std=c++11 -ithird-party/easyloggingpp -ithird-party/glad -ithird-party/sqlite -ithird-party/imgui -ithird-party/glfw -ithird-party/hidapi &> cppcheck_run.log
+          cppcheck . --std=c++11 -ithird-party/easyloggingpp -ithird-party/glad -ithird-party/sqlite -ithird-party/imgui -ithird-party/glfw -ithird-party/hidapi --xml &> cppcheck_run.log
 
       - name: Upload cppcheck log
         uses: actions/upload-artifact@v3
@@ -434,9 +434,11 @@ jobs:
       - name: Provide correct exit status for job 
         shell: bash
         run: |
-          if [ ${{steps.cppcheck_run.outcome}} = "failure" ];then
-             echo "cppcheck_run failed, please open it to view the reported issue"
-             exit 1
+          ERROR_COUNT=$(grep ccpcheck_run.log -e "severity=\"error\"" -c)
+          if [ $ERROR_COUNT == 21 ];
+          then
+            echo "cppcheck_run failed, please open it to view the reported issue"
+            exit 1
           else
-             exit 0
+            exit 0
           fi
