error print was changed

diff --git a/.github/workflows/static_analysis.yaml b/.github/workflows/static_analysis.yaml
--- a/.github/workflows/static_analysis.yaml
+++ b/.github/workflows/static_analysis.yaml
@@ -129,13 +129,6 @@ jobs:
           
           # Retrieve CMake minimal version from the last line of the tool output.
           current_cmake_version=$(echo ${output: -30} | cut -d'(' -f 2 | head -c -2)
-          
-          regex_pattern="VERSION [0-9]+\.[0-9]+\.[0-9]+"
-          if ! [[ "$current_cmake_version" =~ $regex_pattern ]];
-          then
-            echo "Error - CMake version $current_cmake_version does not match the pattern VERSION dd.dd.dd"
-            exit 1
-          fi  
 
           # Saving cmake minimal version string in GitHub output
           echo "current_cmake_version=$current_cmake_version" >> $GITHUB_OUTPUT
@@ -146,10 +139,17 @@ jobs:
           CURRENT_CMAKE_VERSION: ${{ steps.cmake_version.outputs.current_cmake_version }}
 
         run: |
+          regex_pattern="VERSION [0-9]+\.[0-9]+\.[0-9]+"
+          if ! [[ "$current_cmake_version" =~ $regex_pattern ]];
+          then
+            echo "Error - CMake version $CURRENT_CMAKE_VERSION does not match the pattern VERSION dd.dd.dd"
+            exit 1
+          fi
+
           if [ "$CURRENT_CMAKE_VERSION" == "${EXPECTED_CMAKE_VERSION}" ] || [ "$CURRENT_CMAKE_VERSION" \< "${EXPECTED_CMAKE_VERSION}" ]
           then
             echo "The test PASSED, current CMake version is $CURRENT_CMAKE_VERSION and it is not higher than ${EXPECTED_CMAKE_VERSION}"
           else
-            echo "Error - LibRS minimally CMake version required is ${EXPECTED_CMAKE_VERSION} but on this build a minimally CMake version is $CURRENT_CMAKE_VERSION"
+            echo "Error - The minimal CMake version required for LibRS is ${EXPECTED_CMAKE_VERSION} but on this build the minimal CMake version that works is $CURRENT_CMAKE_VERSION"
             exit 1
           fi              
